# Generated by Django 2.1.4 on 2018-12-14 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cotacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uasg', models.TextField()),
                ('numero', models.TextField()),
                ('objeto', models.TextField()),
                ('data_abertura', models.TextField()),
                ('observacoes', models.TextField()),
                ('situacao', models.TextField()),
                ('data_encerramento', models.TextField()),
                ('hora_encerramento', models.TextField()),
                ('valor_maximo', models.TextField()),
            ],
        ),
    ]
