# Generated by Django 2.1.4 on 2018-12-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='link',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
