# Generated by Django 2.1.4 on 2019-02-12 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotacao', '0003_listapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotacao',
            name='atualizado',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
